-- Assessment Gate 3.1: durable execution-kernel persistence.
--
-- UP: this migration is additive and idempotent. It stores the existing
-- orchestrator domain objects without modifying authoritative runtime contracts
-- or the legacy jobs/receipts tables.

CREATE TABLE IF NOT EXISTS orchestrator_runs (
  run_id TEXT PRIMARY KEY,
  workflow_type TEXT NOT NULL,
  priority TEXT NOT NULL,
  state TEXT NOT NULL CHECK (
    state IN (
      'requested', 'scheduled', 'attempt_created', 'leased', 'running',
      'completed', 'failed', 'cancelling', 'cancelled', 'waiting_for_hitl'
    )
  ),
  aggregate_version INTEGER NOT NULL DEFAULT 0 CHECK (aggregate_version >= 0),
  trace_id TEXT NOT NULL,
  request_id TEXT NOT NULL,
  principal_id TEXT NOT NULL,
  current_attempt_id TEXT,
  current_lease_id TEXT,
  last_event_id TEXT,
  last_receipt_id TEXT,
  created_at TIMESTAMPTZ NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_orchestrator_runs_state_created
  ON orchestrator_runs(state, created_at, run_id);

CREATE TABLE IF NOT EXISTS orchestrator_commands (
  idempotency_key TEXT PRIMARY KEY,
  command_id TEXT NOT NULL UNIQUE,
  run_id TEXT NOT NULL REFERENCES orchestrator_runs(run_id) ON DELETE RESTRICT,
  command_type TEXT NOT NULL CHECK (
    command_type IN ('execution.submit', 'schedule', 'cancel', 'pause', 'resume', 'checkpoint')
  ),
  workflow_type TEXT NOT NULL,
  priority TEXT NOT NULL,
  input JSONB NOT NULL DEFAULT '{}'::jsonb,
  request_id TEXT NOT NULL,
  trace_id TEXT NOT NULL,
  principal_id TEXT NOT NULL,
  issued_at TIMESTAMPTZ NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_orchestrator_commands_run
  ON orchestrator_commands(run_id);

CREATE TABLE IF NOT EXISTS orchestrator_leases (
  lease_id TEXT PRIMARY KEY,
  run_id TEXT NOT NULL REFERENCES orchestrator_runs(run_id) ON DELETE CASCADE,
  attempt_id TEXT NOT NULL,
  executor_id TEXT NOT NULL,
  acquired_at TIMESTAMPTZ NOT NULL,
  expires_at TIMESTAMPTZ NOT NULL,
  CHECK (expires_at > acquired_at)
);

CREATE INDEX IF NOT EXISTS idx_orchestrator_leases_active
  ON orchestrator_leases(run_id, expires_at DESC);

CREATE TABLE IF NOT EXISTS orchestrator_events (
  event_id TEXT PRIMARY KEY,
  run_id TEXT NOT NULL REFERENCES orchestrator_runs(run_id) ON DELETE CASCADE,
  event_type TEXT NOT NULL,
  aggregate_version INTEGER NOT NULL CHECK (aggregate_version > 0),
  global_event_index BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
  occurred_at TIMESTAMPTZ NOT NULL,
  payload JSONB NOT NULL DEFAULT '{}'::jsonb,
  payload_hash TEXT NOT NULL,
  previous_global_hash TEXT,
  global_hash TEXT NOT NULL,
  UNIQUE (run_id, aggregate_version)
);

CREATE INDEX IF NOT EXISTS idx_orchestrator_events_run_version
  ON orchestrator_events(run_id, aggregate_version);

CREATE TABLE IF NOT EXISTS orchestrator_receipts (
  receipt_id TEXT PRIMARY KEY,
  run_id TEXT NOT NULL REFERENCES orchestrator_runs(run_id) ON DELETE CASCADE,
  event_id TEXT NOT NULL UNIQUE REFERENCES orchestrator_events(event_id) ON DELETE RESTRICT,
  logical_clock INTEGER NOT NULL CHECK (logical_clock > 0),
  receipt_type TEXT NOT NULL,
  previous_hash TEXT,
  state_hash TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL,
  UNIQUE (run_id, logical_clock)
);

CREATE INDEX IF NOT EXISTS idx_orchestrator_receipts_run_clock
  ON orchestrator_receipts(run_id, logical_clock);

-- The named sequence is reserved by PostgreSQL for the identity column above.
-- `PostgresExecutionRepository` serializes event-chain assignment with an
-- advisory transaction lock and allocates from this sequence before hashing.

-- DOWN (manual, only after retention review):
-- DROP TABLE IF EXISTS orchestrator_receipts;
-- DROP TABLE IF EXISTS orchestrator_events;
-- DROP TABLE IF EXISTS orchestrator_leases;
-- DROP TABLE IF EXISTS orchestrator_commands;
-- DROP TABLE IF EXISTS orchestrator_runs;
