apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: mea
type: Opaque
stringData:
  POSTGRES_DB: mea
  POSTGRES_USER: mea
  POSTGRES_PASSWORD: changeme  # CHANGE THIS IN PRODUCTION
